#!/bin/bash
cp -r chatapplication /home/ubuntu
cd /home/ubuntu/
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-venv
python3 -m venv env
source env/bin/activate
cd /home/ubuntu/chatapplication/
pip3 install setuptools_rust
pip3 install -r req.txt
pip3 install channels
sudo apt-get install -y libmysqlclient-dev
pip3 install mysqlclient
pip3 install django-environ 
